apiVersion: v1
entries:
  kbase:
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2024-11-30T22:57:13.445126307Z"
    description: A Helm chart for Kubernetes
    digest: cca2107373478e3393bfb498901e194309c3b6a501797119de2f6a657dc1c28e
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-1.0.9.tgz
    version: 1.0.9
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2024-11-30T22:57:13.444705156Z"
    description: A Helm chart for Kubernetes
    digest: e05d4473bc02392e483da2ec8a59d915e86521bff813bf7968b509bc29173d82
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-1.0.8.tgz
    version: 1.0.8
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2024-11-30T22:57:13.44431285Z"
    description: A Helm chart for Kubernetes
    digest: 147217341726f9b9db1454f7bb7af5a488f1ad4c99a63ef6ff7c70e8c3d6047e
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-1.0.7.tgz
    version: 1.0.7
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2024-11-30T22:57:13.44392431Z"
    description: A Helm chart for Kubernetes
    digest: 31889d8c69961f9d504292cc73099830faa1b216eb733b5eb185813170f6a4ce
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-1.0.6.tgz
    version: 1.0.6
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2024-11-30T22:57:13.443533556Z"
    description: A Helm chart for Kubernetes
    digest: 9f81b4f7558781357c7eed8adedc5882f301af423fbe02288962c037596e032e
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-1.0.5.tgz
    version: 1.0.5
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2024-11-30T22:57:13.443129738Z"
    description: A Helm chart for Kubernetes
    digest: 51caf07247182f7b9e0daccf9b739459e6dbafa5778906b415b3abc0ced7d7af
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-1.0.4.tgz
    version: 1.0.4
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2024-11-30T22:57:13.442546633Z"
    description: A Helm chart for Kubernetes
    digest: 96ab8e2835e6b78998a7896be7277081c3a2e95b0c073b8808e16a915d5fea38
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2024-11-30T22:57:13.441841289Z"
    description: A Helm chart for Kubernetes
    digest: 9260459396f1316ae907bf9bb78ddbf660a09d7c20167c40b535b72dff913753
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: 0.1.7
    created: "2024-11-30T22:57:13.441189625Z"
    description: A Helm chart for Kubernetes
    digest: c4af59fc2d4a4363b394a725336613f026bde9b8ffbab8f513746b616f18ce16
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 0.1.7
    created: "2024-11-30T22:57:13.440748086Z"
    description: A Helm chart for Kubernetes
    digest: 8b24858043858acdadd584487dbacd32f54e96b63de993b708b78938c704e796
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.2.9.tgz
    version: 0.2.9
  - apiVersion: v2
    appVersion: 0.1.7
    created: "2024-11-30T22:57:13.440315123Z"
    description: A Helm chart for Kubernetes
    digest: c6665530688f474dca3bc44ac922f27b7f5aff1137d30877269984f965dd1d79
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.2.8.tgz
    version: 0.2.8
  - apiVersion: v2
    appVersion: 0.1.7
    created: "2024-11-30T22:57:13.439852815Z"
    description: A Helm chart for Kubernetes
    digest: 854a36768053db79f1b1e0b62df70bf43a7ef95f0ae50815802cf9479f91898b
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.2.7.tgz
    version: 0.2.7
  - apiVersion: v2
    appVersion: 0.1.7
    created: "2024-11-30T22:57:13.438715102Z"
    description: A Helm chart for Kubernetes
    digest: 8aa4a11d5993cb63ae98deb579858caa300dd1bbeb792d51f6f49be8d194e613
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.2.6.tgz
    version: 0.2.6
  - apiVersion: v2
    appVersion: 0.1.7
    created: "2024-11-30T22:57:13.438324909Z"
    description: A Helm chart for Kubernetes
    digest: dc0ba02dbd028ce648ba64976e58e7ca212f0e84bd9bdc4d8f0c184ad3946a66
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.2.5.tgz
    version: 0.2.5
  - apiVersion: v2
    appVersion: 0.1.6
    created: "2024-11-30T22:57:13.437895924Z"
    description: A Helm chart for Kubernetes
    digest: 4bf441278cfac6734fee74f0abb08433716de967f7d754d44b31a3ba9074de7b
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.2.4.tgz
    version: 0.2.4
  - apiVersion: v2
    appVersion: 0.1.5
    created: "2024-11-30T22:57:13.437511793Z"
    description: A Helm chart for Kubernetes
    digest: 01b0d340d46be7fedd94ca0cd1bb44b02140d726fce057a1f5f74ba27c8781f5
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: 0.1.4
    created: "2024-11-30T22:57:13.437125487Z"
    description: A Helm chart for Kubernetes
    digest: 5eaaa25259598d83a5e031c584ad6907f35c6ef4ca63552a786266511208e5ac
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: 0.1.4
    created: "2024-11-30T22:57:13.436709466Z"
    description: A Helm chart for Kubernetes
    digest: 9a24cae9ef95ed0d30d2e9d8f6a67d9f5f12b05eca58c7d1331b85bf1378bce4
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 0.1.4
    created: "2024-11-30T22:57:13.434023532Z"
    description: A Helm chart for Kubernetes
    digest: cdebcc64c18dfe089f46b21d93ce123deab964728a8f333151914f229f7839ac
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.34.tgz
    version: 0.1.34
  - apiVersion: v2
    appVersion: 0.1.3
    created: "2024-11-30T22:57:13.433621969Z"
    description: A Helm chart for Kubernetes
    digest: be5c57e4aaacb6b4dc89dc2ee2078689f7ea660e61ed7a7940a9bb78e9250487
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.33.tgz
    version: 0.1.33
  - apiVersion: v2
    appVersion: 0.1.2
    created: "2024-11-30T22:57:13.433178536Z"
    description: A Helm chart for Kubernetes
    digest: cb78d363fda69e7881d5ad76401ddf32ae1ed63ad45b852171ef67c4d1f9579d
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.32.tgz
    version: 0.1.32
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2024-11-30T22:57:13.432196107Z"
    description: A Helm chart for Kubernetes
    digest: 052bdbd296c4a955ed63c67e40262a93002e7636210df6e6defb8be2d3a31e9d
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.31.tgz
    version: 0.1.31
  - apiVersion: v2
    appVersion: 0.0.22
    created: "2024-11-30T22:57:13.431618242Z"
    description: A Helm chart for Kubernetes
    digest: 56e0d2b1e8fdaab6f1204c60210478df13cd27a08b423c3539cfb5f2ef2387ed
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.30.tgz
    version: 0.1.30
  - apiVersion: v2
    appVersion: 0.0.22
    created: "2024-11-30T22:57:13.430840172Z"
    description: A Helm chart for Kubernetes
    digest: 8f563c9043418eee6a37b036ec3d4518b2ff8c3fcbb80027d3a9bebd759a5c6f
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.29.tgz
    version: 0.1.29
  - apiVersion: v2
    appVersion: 0.0.21
    created: "2024-11-30T22:57:13.430442926Z"
    description: A Helm chart for Kubernetes
    digest: 75b25b2c20923dd80fa6f89a7b6cadd3546b483231a266c3c593101031f27e73
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.28.tgz
    version: 0.1.28
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T22:57:13.430053965Z"
    description: A Helm chart for Kubernetes
    digest: 8731c327bf9a3e99aae01f889522375217f2052218021ba2e7fdf1e96c0a15d8
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.27.tgz
    version: 0.1.27
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T22:57:13.429674052Z"
    description: A Helm chart for Kubernetes
    digest: 367a6c706326ba3f5e342b1adfd7b701c6d708ff53a36cdb1f23abc50ba1a5a0
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.26.tgz
    version: 0.1.26
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T22:57:13.429289169Z"
    description: A Helm chart for Kubernetes
    digest: 73d005797cfb715bd1c4822d07cee9c7344c6301b6884149fd37effa998db9b8
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.25.tgz
    version: 0.1.25
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T22:57:13.428865934Z"
    description: A Helm chart for Kubernetes
    digest: 1425199aab2f7a70969b9046a9d7bd589aed1fcd59b82dac72fa23fea4a3b9bd
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.24.tgz
    version: 0.1.24
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T22:57:13.428470932Z"
    description: A Helm chart for Kubernetes
    digest: 554f600ed900c2146090d915377ab1cf7dd107957738e72da4d6d501facbf33d
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.23.tgz
    version: 0.1.23
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T22:57:13.42792075Z"
    description: A Helm chart for Kubernetes
    digest: 079217cd98c13b93f388e28ddcd1acb991cf0b4bb9cf4272cadd856417869230
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.22.tgz
    version: 0.1.22
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T22:57:13.427536798Z"
    description: A Helm chart for Kubernetes
    digest: 753348ae34d3efe4b52ea39ee396e7549adf6f9bb2c9960e067553d92007af90
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.21.tgz
    version: 0.1.21
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T22:57:13.427141917Z"
    description: A Helm chart for Kubernetes
    digest: 8135fa4b8ffc964b579a6056223c59e36bdc74cb4b70a0ee5449df41b4db551b
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.20.tgz
    version: 0.1.20
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T22:57:13.426346002Z"
    description: A Helm chart for Kubernetes
    digest: bcaba59577fd02ccc83b6cc4d821fee4534d2298b1c9d95fa9d8ba7e066d439c
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.19.tgz
    version: 0.1.19
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T22:57:13.425630247Z"
    description: A Helm chart for Kubernetes
    digest: 0267a7d6267f59245db4ba25c7bdb6f7df2ace107eaeda21cb410db920815e6b
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.18.tgz
    version: 0.1.18
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2024-11-30T22:57:13.424621222Z"
    description: A Helm chart for Kubernetes
    digest: 448980aa12946c13b40ac996adbd14baf2a6ff2270cd240a510061a8493f422b
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.17.tgz
    version: 0.1.17
  - apiVersion: v2
    appVersion: 0.0.18
    created: "2024-11-30T22:57:13.424236129Z"
    description: A Helm chart for Kubernetes
    digest: 5329adf52027811b785c28a31c22f6cf3923020ea0be323348af1d126983139f
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.16.tgz
    version: 0.1.16
  - apiVersion: v2
    appVersion: 0.0.18
    created: "2024-11-30T22:57:13.423845456Z"
    description: A Helm chart for Kubernetes
    digest: b91811df41356d645366dbdee6cb546dde49c77f520a2cd3a66b56c573878702
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.15.tgz
    version: 0.1.15
  - apiVersion: v2
    appVersion: 0.0.18
    created: "2024-11-30T22:57:13.423453509Z"
    description: A Helm chart for Kubernetes
    digest: 469dba6702ec59172f69f9dba62d6b93e893fd8eee343103da183989f3b59cbf
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.14.tgz
    version: 0.1.14
  - apiVersion: v2
    appVersion: 0.0.17
    created: "2024-11-30T22:57:13.423056183Z"
    description: A Helm chart for Kubernetes
    digest: 61e9bded727f76c914a1576bfffb407fd2e8ff929058049d74d761b28fd12969
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.13.tgz
    version: 0.1.13
  - apiVersion: v2
    appVersion: 0.0.13
    created: "2024-11-30T22:57:13.422658928Z"
    description: A Helm chart for Kubernetes
    digest: eb1ba38ad2801ea732622b4f9f3934e2551b6522b69a33ea0511c44408a457c2
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.12.tgz
    version: 0.1.12
  - apiVersion: v2
    appVersion: 0.0.13
    created: "2024-11-30T22:57:13.42225572Z"
    description: A Helm chart for Kubernetes
    digest: 54dfe0506fc6de4751f88c598be538c3d0ea3af328cf39c6ecaef3f867b6ce33
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.11.tgz
    version: 0.1.11
  - apiVersion: v2
    appVersion: 0.0.13
    created: "2024-11-30T22:57:13.421848616Z"
    description: A Helm chart for Kubernetes
    digest: 7756650e7fdb9f398a8ab15c90e001be074a1f08fa567194089c187bd315fdc4
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.10.tgz
    version: 0.1.10
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T22:57:13.436329583Z"
    description: A Helm chart for Kubernetes
    digest: c76b2fb7965802cc1a9f8261ec9a83175430710c666e4a613733d59f5849f100
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T22:57:13.435948858Z"
    description: A Helm chart for Kubernetes
    digest: 72e9223c806fe96e7eb68a53b7fc588686c54e0c41406292483e26f4148822d0
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T22:57:13.435569175Z"
    description: A Helm chart for Kubernetes
    digest: 3324820becbbe4d5e57a3a6e1508f22b8baa3b9745c9071e7dc2a52a0350315b
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T22:57:13.435187799Z"
    description: A Helm chart for Kubernetes
    digest: b011a603a4b30a1c1a48462567990934c32b3f05744ab1b117023647a0ee666e
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T22:57:13.434801153Z"
    description: A Helm chart for Kubernetes
    digest: 7cdf6d686301b6dc79be0601934da34b3c84b952709e2c428def36cb3e3a5e44
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 0.0.11
    created: "2024-11-30T22:57:13.434416029Z"
    description: A Helm chart for Kubernetes
    digest: 43230d907d41bf98403f3e17224f16fdfb7e376dbf4d1658dab7ab61e422c5d4
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 0.0.10
    created: "2024-11-30T22:57:13.431225475Z"
    description: A Helm chart for Kubernetes
    digest: 53cc0d55896b9378e24ddda6263dc78c1eb0fbb6c5045a738351fad9816c8bb7
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.0.10
    created: "2024-11-30T22:57:13.426751073Z"
    description: A Helm chart for Kubernetes
    digest: a63fc516ef96a5f905fed85d465311f0ffb9e548bb323170b2fa26c5feafba28
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.0.10
    created: "2024-11-30T22:57:13.421434097Z"
    description: A Helm chart for Kubernetes
    digest: 28e6b43b6adf406c8d177e126b39db870d558268b31b828469339a8ffdfaec85
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2024-11-30T22:57:13.420984503Z"
    description: A Helm chart for Kubernetes
    digest: 7f1bc5f3c6be37c36b0ea12177c442bfe2f9827c217df4566d623d94550d964a
    name: kbase
    type: application
    urls:
    - https://jackwilde.github.io/kbase/kbase-0.1.0.tgz
    version: 0.1.0
generated: "2024-11-30T22:57:13.420392251Z"
